AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - GET
          - POST

  FfmpegVersionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FfmpegVersionFunction
      Handler: main
      Runtime: provided.al2023
      Architectures:
        - arm64
      CodeUri: deployment/ffmpeg-version/deployment.zip
      MemorySize: 128
      Timeout: 5
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /ffmpeg-version
            Method: GET

  Video2GifFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Video2GifFunction
      Handler: main
      Runtime: provided.al2023
      Architectures:
        - arm64
      CodeUri: deployment/video2gif/deployment.zip
      MemorySize: 1024
      Timeout: 29
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource:
                - arn:aws:s3:::iamtestingmys3/*
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /video2gif
            Method: GET
      Environment:
        Variables:
          PATH: "/var/task/bin:/usr/bin:/usr/local/bin:/bin"

Outputs:
  ApiUrl:
    Description: Base URL for the API Gateway
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
    Export:
      Name: ApiUrl
